import { StyleSheet } from "react-native";

/** Shared light shell styles so module panels match Home / Settings. */
export const modulePanelStyles = StyleSheet.create({
  panel: {
    backgroundColor: "#ffffff",
    borderColor: "#dce7e3",
    borderWidth: 1,
    borderRadius: 24,
    padding: 16,
    gap: 12,
  },
  panelTitle: { color: "#17211e", fontSize: 20, fontWeight: "900" },
  muted: { color: "#6c7b76", fontSize: 13, lineHeight: 19 },
  input: {
    backgroundColor: "#f8fbfa",
    borderColor: "#dce7e3",
    borderWidth: 1,
    borderRadius: 16,
    color: "#17211e",
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
  },
  primaryButton: {
    backgroundColor: "#0f8f6f",
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: "center",
  },
  primaryButtonText: { color: "#ffffff", fontWeight: "900", fontSize: 15 },
  secondaryButton: {
    borderColor: "#0f8f6f",
    borderWidth: 1,
    borderRadius: 16,
    paddingVertical: 12,
    alignItems: "center",
    backgroundColor: "#ffffff",
  },
  secondaryButtonText: { color: "#0b6f58", fontWeight: "800" },
  rowBetween: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  linkText: { color: "#0f8f6f", fontWeight: "800" },
  grid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  metricCard: {
    flexGrow: 1,
    minWidth: "45%",
    backgroundColor: "#f8fbfa",
    borderRadius: 18,
    padding: 12,
    borderWidth: 1,
    borderColor: "#dce7e3",
  },
  metricLabel: { color: "#6c7b76", fontSize: 12, fontWeight: "700" },
  metricValue: { color: "#17211e", fontSize: 18, fontWeight: "900", marginTop: 6 },
  statusRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  statusPill: {
    color: "#0b6f58",
    backgroundColor: "#e0f4ed",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 12,
    fontWeight: "800",
    overflow: "hidden",
  },
  ok: { backgroundColor: "#0f8f6f", color: "#ffffff" },
  failed: { backgroundColor: "#fee9e9", color: "#dc2626" },
  listRow: { borderTopColor: "#dce7e3", borderTopWidth: 1, paddingTop: 10, gap: 2 },
  listTitle: { color: "#17211e", fontWeight: "900", fontSize: 15 },
  sectionLabel: { color: "#0b6f58", fontWeight: "900", marginTop: 6 },
  tabRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  tabButton: {
    backgroundColor: "#f8fbfa",
    borderColor: "#dce7e3",
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  tabButtonActive: { backgroundColor: "#0f8f6f", borderColor: "#0f8f6f" },
  tabButtonText: { color: "#6c7b76", fontWeight: "800", fontSize: 12 },
  tabButtonTextActive: { color: "#ffffff" },
});
